// <auto-generated />
using System;
using Iris.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Iris.Server.Data.Migrations
{
    [DbContext(typeof(IrisDbContext))]
    partial class IrisDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Iris.Server.Data.Entities.ActivityEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<string>("ActivityType")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Document")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.HasKey("Id");

                    b.HasIndex("ActivityType");

                    b.ToTable("Activities", (string)null);
                });

            modelBuilder.Entity("Iris.Server.Data.Entities.ActorEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Document")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Handle")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Type")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.HasIndex("Handle");

                    b.ToTable("Actors", (string)null);
                });

            modelBuilder.Entity("Iris.Server.Data.Entities.BoxItemEntity", b =>
                {
                    b.Property<int>("Direction")
                        .HasColumnType("integer");

                    b.Property<string>("ActorId")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<string>("ItemIri")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<long>("Position")
                        .HasColumnType("bigint");

                    b.HasKey("Direction", "ActorId", "ItemIri");

                    b.ToTable("BoxItems", (string)null);
                });

            modelBuilder.Entity("Iris.Server.Data.Entities.CreateIndexEntity", b =>
                {
                    b.Property<string>("ObjectId")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<string>("CreateActivityId")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.HasKey("ObjectId");

                    b.ToTable("CreateIndex", (string)null);
                });

            modelBuilder.Entity("Iris.Server.Data.Entities.EdgeEntity", b =>
                {
                    b.Property<int>("Kind")
                        .HasColumnType("integer");

                    b.Property<string>("Source")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<string>("Target")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Kind", "Source", "Target");

                    b.HasIndex("Kind", "Target");

                    b.HasIndex("Kind", "Source", "Target")
                        .IsUnique();

                    b.ToTable("Edges", (string)null);
                });

            modelBuilder.Entity("Iris.Server.Data.Entities.KeyEntity", b =>
                {
                    b.Property<string>("KeyId")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<string>("Algorithm")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("PrivateKeyPem")
                        .HasColumnType("text");

                    b.Property<string>("PublicKeyPem")
                        .HasColumnType("text");

                    b.HasKey("KeyId");

                    b.ToTable("Keys", (string)null);
                });

            modelBuilder.Entity("Iris.Server.Data.Entities.MediaEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FileName")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("StorageKey")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.HasKey("Id");

                    b.HasIndex("Id");

                    b.ToTable("Media", (string)null);
                });

            modelBuilder.Entity("Iris.Server.Data.Entities.ObjectEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<string>("AttributedTo")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Document")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<bool>("IsTombstoned")
                        .HasColumnType("boolean");

                    b.Property<string>("ObjectType")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.HasIndex("AttributedTo");

                    b.ToTable("Objects", (string)null);
                });

            modelBuilder.Entity("Iris.Server.Data.Entities.UserAccountEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ActorIri")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("NotificationsReadAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.HasIndex("ActorIri");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("UserAccounts", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
